dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.11.0/bazel_0.11.0-linux-x86_64.deb
  - sha256sum -c tools/ci/bazel_0.11.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.11.0-linux-x86_64.deb

script:
  - tools/ci/run_ci_tests.sh
