#!/bin/bash
set -e
# bazel --batch test //src/...
bazel --bazelrc=tools/ci/bazelrc_travis build //src/... //deploy/...
bazel --bazelrc=tools/ci/bazelrc_travis build //src/... //deploy/... --crosstool_top=//compilers/arm_compiler:toolchain --cpu=rpi
