#!/bin/bash
set -e
# bazel --batch test //src/...
bazel --bazelrc=tools/ci/bazelrc_travis build //...
bazel --bazelrc=tools/ci/bazelrc_travis build //... --crosstool_top=//compilers/arm_compiler:toolchain --cpu=rpi
